version: "3.7"

networks:
  mynetwork:
    name: mynetwork
    attachable: true

services:

  app:
    container_name: spring-app
    image: docker.io/library/demo:0.0.1-SNAPSHOT
    networks:
      - mynetwork

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - mynetwork


  keycloak:
    container_name: auth
    image: jboss/keycloak:12.0.4
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      # Uncomment the line below if you want to specify JDBC parameters.
      # The parameter below is just an example, and it shouldn't be used in production without knowledge.
      # It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 18080:8080
    depends_on:
      - postgres
    networks:
      - mynetwork

  nginx:
    container_name: proxy
    build: ./openresty
    ports:
      - 80:80
    networks:
      - mynetwork
    volumes:
      - ./openresty/nginx-auth-cc-flow.conf:/etc/nginx/conf.d/default.conf
      - ./openresty/client-credentials-flow.lua:/usr/local/openresty/site/lualib/client-credentials-flow.lua
      - ./openresty/repository/auth2_resp_repos.lua:/usr/local/openresty/site/lualib/repository/auth2_resp_repos.lua